version: '3.8'

services:
  spring-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/finance_management_app
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: pufiursulica

#  postgres-db:
#    image: postgres:16
#    container_name: finance_management-db
#    environment:
#      POSTGRES_DB: finance_management_app
#      POSTGRES_USER: postgres
#      POSTGRES_PASSWORD: pufiursulica
#    ports:
#      - "5432:5432"
#    volumes:
#      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
